
const data = {
    products: [
        {
            name: 'Free Shirt',
            slug: 'free-shirt',
            category: 'Shirts',
            image: '/images/shirt1.jpg',
            price: 70,
            brand: 'Niky',
            rating: 4.5,
            numReviews: 8,
            countInStock: 20,
            description:  'A free shirt',
        },
        {
            name: 'Fit Shirt',
            slug: 'fit-shirt',
            category: 'Shirts',
            image: '/images/shirt2.jpg',
            price: 80,
            brand: 'Ardidas',
            rating: 3.2,
            numReviews: 10,
            countInStock: 20,
            description:  'A fit shirt',
        },
        {
            name: 'Slim Shirt',
            slug: 'slim-shirt',
            category: 'Shirts',
            image: '/images/shirt3.jpg',
            price: 90,
            brand: 'Raimundo',
            rating: 4.5,
            numReviews: 3,
            countInStock: 20,
            description:  'A slim shirt',
        },
        {
            name: 'Golf Pants',
            slug: 'golf-pants',
            category: 'Pants',
            image: '/images/pants1.jpg',
            price: 90,
            brand: 'Olivas',
            rating: 2.9,
            numReviews: 13,
            countInStock: 20,
            description:  'A golf pants',
        },
        {
            name: 'Fit Pants',
            slug: 'fit-pants',
            category: 'Pants',
            image: '/images/pants2.jpg',
            price: 95,
            brand: 'Zarai',
            rating: 3.5,
            numReviews: 7,
            countInStock: 20,
            description:  'A fit pants',
        },
        {
            name: 'Classic Pants',
            slug: 'classic-pants',
            category: 'Pants',
            image: '/images/pants3.jpg',
            price: 75,
            brand: 'Porscha',
            rating: 2.4,
            numReviews: 14,
            countInStock: 20,
            description:  'A classic pants',
        },
    ]
}

export default data;